### PR TITLE
1 more try

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
@villfa Success: https://github.com/szepeviktor/test-phar-gpg/runs/1400536602?check_suite_focus=true
🍏

**Comment by szepeviktor** [comment]
You need to remove the password from your private key: `gpg --edit-key 152CDA4D552E1E67 passwd`

**Comment by villfa** [comment]
Thanks a lot! :)

**Comment by szepeviktor** [comment]
You're welcome.

Please consider using/publishing a separate PHAR signing key in CI, not you personal GPG key.

**Pull request closed without merging**
